config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:edit, :update, :show, :destroy]
  before_action :image_url, only: [:index, :show]
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(set_params)
    if @flat.save
      redirect_to flats_path
    else
      render:new
    end
  end

  def show
    @url = "https://maps.googleapis.com/maps/api/staticmap?center=#{@flat.address}&zoom=14&size=1000x1000"
  end

  def update
    @flat.update(set_params).save
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private
  def set_flat
    @flat = Flat.find(params[:id])
  end

  def set_params
    params.require('flat').permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def image_url
    @image = ['https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200', 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200', 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200', 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200', 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_card.html.erb
<div class="card-with-margin">
  <div class="card">
    <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%=locals[:image][locals[:flat].id - 1]%>);"></div>
    <div class="card-description">
      <h2><%= locals[:flat].name %></h2>
      <p><%= locals[:flat].description %></p>
      <i class="fas fa-user-plus">   <%= locals[:flat].number_of_guests %></i>
      <i class="fas fa-dollar-sign">   <%= locals[:flat].price_per_night %></i>

    </div>
    <div>
      <%= render "footer", flat:locals[:flat]%>
    </div>
  </div>

</div>

app/views/flats/_footer.html.erb
<div class="footer">
  <p class="more"><%= link_to "More info", flat_path(flat) %></p>
  <p class="edit"><%= link_to "Edit", edit_flat_path(flat) %></p>
  <p class="remove"><%= link_to "Remove", flat_path(flat), method: :delete %></p>
</div>

app/views/flats/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
          <%= simple_form_for [flat] do |f|%>
            <%= f.input :name %>
            <%= f.input :address %>
            <%= f.input :description %>
            <%= f.input :price_per_night %>
            <%= f.input :number_of_guests %>
            <%= f.submit "Add a new flat", :class => "btn btn-success" %>
            <%= link_to "cancle", flats_path, :class => "btn btn-cancle" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/edit.html.erb
<h2 class="for-form">Edit the flat</h2>
<%= render 'form', flat:@flat %>

app/views/flats/index.html.erb
<div class="container">

  <h2 class="for-form">All our Flats</h2>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-xs-12 col-sm-4">
        <%= render 'card', locals:{ flat: flat, image:@image } %>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h2 class="for-form">Add a new flat</h2>
<%= render 'form', flat:@flat %>

app/views/flats/show.html.erb
<div class="map" style="background-image: url(<%= @image[@flat.id - 1] %>)">  </div>
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="show-card">
        <h1><%= @flat.name %></h1>
        <p><%= @flat.address  %></p>
      </div>
      <div class="show-card">
        <h3>A bit more about this flat</h3>
        <p><%= @flat.description %></p>
        <div>
          <%= image_tag @url%>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="show-card">
        <strong><h5>Book this place!</h5></strong>
        <form action="">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-addon" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success" style="width: 100%">
        </form>
      </div>
      <div class="show-card">
        <h3>Details</h3>
        <i class="fas fa-user-plus">      <%= @flat.number_of_guests %></i>
        <i class="fas fa-dollar-sign">   <%= @flat.price_per_night %></i>
      </div>
      <div class="show-card">
        <div class="row-for-share">
          <h6>Share</h6>
          <div class="flex">
            <i class="fab fa-facebook"></i>
            <i class="fab fa-twitter"></i>
            <i class="fab fa-pinterest-square"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

  <h4>Simple Airbnb</h4>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <form class="form-inline" action="">
      <div class="form-group">
        <input class="form-control" placeholder="Search">
        <button class="btn btn-search" type="submit">Search</button>
      </div>
    </form>
    <%= link_to "Add Flat", new_flat_path, class: "btn" %>
  </div>
</div>
<!-- , { :class=>"btn-treehouse} -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render "layouts/navbar"  %>
    <%= yield %>

  </body>
</html>